### ISSUE TITLE
Version 1.0.11 broke execution of embed mongo 3.4.6

### ISSUE THREAD

**Issue by antonioT90** [flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver#3]
Today my test execution downloaded this new version instead of 1.0.10 and they thrown this exception:

`Caused by: java.lang.IncompatibleClassChangeError: Found interface de.flapdoodle.os.Platform, but class was expected
	at de.flapdoodle.embed.mongo.packageresolver.PlatformMatch.match(PlatformMatch.java:58)
	at de.flapdoodle.embed.mongo.packageresolver.PlatformMatch.match(PlatformMatch.java:54)
	at de.flapdoodle.embed.mongo.packageresolver.PackageFinderRules.packageFor(PackageFinderRules.java:44)
	at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.packageFor(PlatformPackageResolver.java:58)
	at de.flapdoodle.embed.process.store.ArtifactStore.filesToExtract(ArtifactStore.java:93)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:84)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:59)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoServer(EmbeddedMongoAutoConfiguration.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 169 common frames omitted`
	
I resolved forcing the dependency to the previous version

This is my execution environment:
`Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /usr/share/apache-maven-3.8.6
Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/temurin-17-jdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-1020-azure", arch: "amd64", family: "unix"
`

**Comment by michaelmosmann** [comment]
@antonioT90 i did a new release of everthing.. 3.5.0 should be in maven central in about 12 or 24hrs..

**Comment by michaelmosmann** [comment]
reopen if problem still exist after update :)
